server:
  port: 8081
spring:
  application:
    name: ms-BillingReports-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/ms_report
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost
feign:
  client:
    config:
      ms-usersubscription-service-user:
        connectTimeout: 5000
        readTimeout: 5000
      ms-usersubscription-service-subscription:
        connectTimeout: 5000
        readTimeout: 5000
