server:
  port: 8085

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-BillingReports-service
          uri: lb://ms-BillingReports-service
          predicates:
            - Path=/billing/**
          filters:
            - AuthFilter
        - id: ms-BillingReports-service-report
          uri: lb://ms-BillingReports-service
          predicates:
            - Path=/report/**
          filters:
            - AuthFilter

        - id: ms-services-service-category
          uri: lb://ms-services-service
          predicates:
            - Path=/category/**
          filters:
            - AuthFilter
        - id: ms-services-service-service
          uri: lb://ms-services-service
          predicates:
            - Path=/service/**
          filters:
            - AuthFilter

        - id: ms-userinteraction-service-notification
          uri: lb://ms-userinteraction-service
          predicates:
            - Path=/notification/**
          filters:
            - AuthFilter
        - id: ms-userinteraction-service-review
          uri: lb://ms-userinteraction-service
          predicates:
            - Path=/review/**
          filters:
            - AuthFilter

        - id: ms-usersubscription-service-subscription
          uri: lb://ms-usersubscription-service
          predicates:
            - Path=/subscription/**
          filters:
            - AuthFilter
        - id: ms-usersubscription-service-user
          uri: lb://ms-usersubscription-service
          predicates:
            - Path=/user/**
          filters:
            - AuthFilter
        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**
