spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ms-usersubscription-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:123456@localhost:7070
